#!/bin/bash

cd ..
rm -rf networking4

git clone https://github.com/semiondu/networking4.git
cp networking4/LB loadBalancer
cp networking4/lb.run loadBalancer
cp networking4/restart loadBalancer
cd loadBalancer
